image: clfoundation/sbcl

stages:
  - test
  - build

# We need to install some system dependencies,
# to clone libraries not in Quicklisp,
# and to update ASDF to >= 3.3.4 in order to use local-package-nicknames.
before_script:
  - apt-get update -qy
  - apt-get install -y git-core sqlite3 tar
  # The image doesn't have Quicklisp installed by default.
  - QUICKLISP_ADD_TO_INIT_FILE=true /usr/local/bin/install-quicklisp
  # clone libraries not in Quicklisp or if we need the latest version.
  - make install
  # Upgrade ASDF. TODO
  - mkdir -p ~/common-lisp/asdf/
  - ( cd ~/common-lisp/asdf/ && wget https://asdf.common-lisp.dev/archives/asdf-3.3.5.lisp && mv asdf-3.3.5.lisp asdf.lisp )
  - echo "Content of ~/common-lisp/asdf/:" && ls ~/common-lisp/asdf/

qa:
  allow_failure: true
  stage: test
  script:
    # QA tools:
    # install Comby:
    - apt-get install -y sudo
    # - bash <(curl -sL get.comby.dev)
    - bash <(curl -sL https://raw.githubusercontent.com/vindarel/comby/set-release-1.0.0/scripts/install.sh)
    # install Colisper:
    - git clone https://github.com/vindarel/colisper ~/colisper
    - chmod +x ~/colisper/colisper.sh
    - alias colisper=~/colisper/colisper.sh  # doesn't work?
    - cd src/ && ~/colisper/colisper.sh

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bookshops
