image: daewok/lisp-devel

stages:
  - build
  - test  # looks like current tests run forever in the CI.

# We need to install (clone) libraries not in Quicklisp.
before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  - make install

build:
  stage: build
  script:
    - make build
