image: clfoundation/sbcl

stages:
  - test  # looks like current tests run forever in the CI.
  - build

# We need to install (clone) libraries not in Quicklisp.
before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  - make install

qa:
  allow_failure: true
  stage: test
  script:
    # QA tools:
    # install Comby:
    - apt-get install -y sudo
    - adduser lisp sudo
    # - bash <(curl -sL get.comby.dev)
    - bash <(curl -sL https://raw.githubusercontent.com/vindarel/comby/set-release-1.0.0/scripts/install.sh)
    # install Colisper:
    - git clone https://github.com/vindarel/colisper ~/colisper
    - chmod +x ~/colisper/colisper.sh
    - alias colisper=~/colisper/colisper.sh  # doesn't work?
    - cd src/ && ~/colisper/colisper.sh

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bookshops
