image: daewok/lisp-devel

stages:
  - build
  - test  # looks like current tests run forever in the CI.

# We need to install (clone) libraries not in Quicklisp.
before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  - make install

  # QA tools:
  - git clone https://github.com/vindarel/colisper ~/colisper
  - alias colisper=~/colisper/colisper.sh

qa:
  allow_failure: true
  stage: test
  script:
    - cd src/ && colisper

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - bookshops
